"use strict";

/*
|--------------------------------------------------------------------------
| ModeloSeeder
|--------------------------------------------------------------------------
|
| Make use of the Factory instance to seed database with dummy data or
| make use of Lucid models directly.
|
*/

/** @type {import('@adonisjs/lucid/src/Factory')} */
const Factory = use("Factory");
const Modelo = use("App/Models/Modelo");
class ModeloSeeder {
  async run() {
    await Modelo.createMany([
      { nome: "Airbus A300" },
      { nome: "Airbus A310 (Airbus A300B100)" },
      { nome: "Airbus A220-100" },
      { nome: "Airbus A220-300" },
      { nome: "Airbus A318" },
      { nome: "Airbus A319" },
      { nome: "Airbus A320" },
      { nome: "Airbus A321" },
      { nome: "Airbus A330" },
      { nome: "Airbus A340" },
      { nome: "Airbus A350" },
      { nome: "Airbus A380" },
      { nome: "Antonov An-24" },
      { nome: "Antonov An-28" },
      { nome: "Antonov An-38" },
      { nome: "Antonov An-140" },
      { nome: "Antonov An-148" },
      { nome: "ATR 42" },
      { nome: "ATR 72" },
      { nome: "BAe 146-300 / Avro RJ100" },
      { nome: "Boeing 247" },
      { nome: "Boeing 307 Stratoliner" },
      { nome: "Boeing 377 Stratocruiser" },
      { nome: "Boeing 707" },
      { nome: "Boeing 717" },
      { nome: "Boeing 720" },
      { nome: "Boeing 727" },
      { nome: "Boeing 737-100" },
      { nome: "Boeing 737-200" },
      { nome: "Boeing 737-300" },
      { nome: "Boeing 737-400" },
      { nome: "Boeing 737-500" },
      { nome: "Boeing 737-600" },
      { nome: "Boeing 737-700" },
      { nome: "Boeing 737-800" },
      { nome: "Boeing 737-900ER" },
      { nome: "Boeing 737-7Max" },
      { nome: "Boeing 737-8MAX" },
      { nome: "Boeing 737-9MAX" },
      { nome: "Boeing 737-10MAX" },
      { nome: "Boeing 747 100" },
      { nome: "Boeing 747 SP" },
      { nome: "Boeing 747-200" },
      { nome: "Boeing 747-300" },
      { nome: "Boeing 747-400" },
      { nome: "Boeing 747-8" },
      { nome: "Boeing 757-200" },
      { nome: "Boeing 757-300" },
      { nome: "Boeing 767-200" },
      { nome: "Boeing 767-200ER" },
      { nome: "Boeing 767-300ER" },
      { nome: "Boeing 767-400ER" },
      { nome: "Boeing 777-200" },
      { nome: "Boeing 777-200ER" },
      { nome: "Boeing 777-300" },
      { nome: "Boeing 777-200LR" },
      { nome: "Boeing 777-300ER" },
      { nome: "Boeing 777-8X" },
      { nome: "Boeing 777-9X" },
      { nome: "Boeing 787-8" },
      { nome: "Boeing 787-9" },
      { nome: "Boeing 787-10" },
      { nome: "Bombardier CRJ-700" },
      { nome: "Bombardier CRJ-900" },
      { nome: "Bombardier CRJ-1000" },
      { nome: "Bombardier Dash 8-100" },
      { nome: "Bombardier Dash 8-200" },
      { nome: "Bombardier Dash 8-300" },
      { nome: "Bombardier Dash 8-400" },
      { nome: "Cessna 208 Caravan" },
      { nome: "Cessna 120" },
      { nome: "Cessna 140" },
      { nome: "Cessna 150" },
      { nome: "Cessna 152" },
      { nome: "Cessna 162 Skycatcher" },
      { nome: "Cessna 165 Airmaster" },
      { nome: "Cessna 172 Skyhawk" },
      { nome: "Cessna 175 Skylark" },
      { nome: "Cessna 177 Cardinal" },
      { nome: "Cessna 180 Skywagon" },
      { nome: "Cessna 182 Skylane" },
      { nome: "Cessna 185 Skywagon" },
      { nome: "Cessna 190" },
      { nome: "Cessna 195" },
      { nome: "Cessna 205 Super Skywagon" },
      { nome: "Cessna 206 Stationair" },
      { nome: "Cessna 210 Centurion" },
      { nome: "Cessna 303" },
      { nome: "Cessna 310" },
      { nome: "Cessna 320 Skynight" },
      { nome: "Cessna 335" },
      { nome: "Cessna 337" },
      { nome: "Cessna 350 Corvalis" },
      { nome: "Cessna 400 Corvalis TT" },
      { nome: "Cessna 402" },
      { nome: "Cessna 404" },
      { nome: "Cessna 406" },
      { nome: "Cessna 411" },
      { nome: "Cessna 414" },
      { nome: "Cessna 421" },
      { nome: "Cessna 425" },
      { nome: "Cessna 441" },
      { nome: "Comac ARJ21" },
      { nome: "Comac C919" },
      { nome: "Concorde" },
      { nome: "Donier Do-228" },
      { nome: "Donier Do-328" },
      { nome: "Douglas DC-2" },
      { nome: "Douglas DC-3" },
      { nome: "Douglas DC-4" },
      { nome: "Douglas DC-6" },
      { nome: "Douglas DC-7" },
      { nome: "Douglas DC-8-10" },
      { nome: "Douglas DC-8-20" },
      { nome: "Douglas DC-8-30" },
      { nome: "Douglas DC-8-40" },
      { nome: "Douglas DC-8-50" },
      { nome: "Douglas DC-8-61" },
      { nome: "Douglas DC-8-62" },
      { nome: "Douglas DC-8-63" },
      { nome: "Douglas DC-9-15" },
      { nome: "Douglas DC-9-21" },
      { nome: "Douglas DC-9-32" },
      { nome: "Douglas DC-9-41" },
      { nome: "Douglas DC-9-51" },
      { nome: "Douglas DC-10" },
      { nome: "Embraer ERJ-135" },
      { nome: "Embraer ERJ-145" },
      { nome: "Embraer ERJ-170" },
      { nome: "Embraer ERJ-175" },
      { nome: "Embraer 175-E2" },
      { nome: "Embraer ERJ-190" },
      { nome: "Embraer 190-E2" },
      { nome: "Embraer ERJ-195" },
      { nome: "Embraer 195-E2" },
      { nome: "Embraer EMB-110 Bandeirante" },
      { nome: "EMB-120 Brasilia" },
      { nome: "Embraer EMB-121 Xingu" },
      { nome: "Embraer CBA-123 Vector" },
      { nome: "Fokker F27" },
      { nome: "Fokker F28" },
      { nome: "Fokker 50" },
      { nome: "Fokker 70" },
      { nome: "Fokker 100" },
      { nome: "Trident 1/1C" },
      { nome: "Trident 1E" },
      { nome: "Trident 2E" },
      { nome: "Trident 3B" },
      { nome: "Let L-410 Turbolet" },
      { nome: "Ilyushin IL-12" },
      { nome: "Ilyushin IL-14" },
      { nome: "llyushin IL-62" },
      { nome: "llyushin IL-86" },
      { nome: "llyushin IL-96-300" },
      { nome: "llyushin IL-96M" },
      { nome: "llyushin IL-96-400" },
      { nome: "llyushin IL-114" },
      { nome: "Lockheed L-1011-100" },
      { nome: "Lockheed L-1011-200" },
      { nome: "Lockheed L-1011-500" },
      { nome: "Lockheed L-188 Electra" },
      { nome: "Lockheed L-10 Electra" },
      { nome: "McDonnell Douglas DC-10" },
      { nome: "McDonnell Douglas MD-11" },
      { nome: "McDonnell Douglas MD-81" },
      { nome: "McDonnell Douglas MD-82" },
      { nome: "McDonnell Douglas MD-83" },
      { nome: "McDonnell Douglas MD-87" },
      { nome: "McDonnell Douglas MD-90-30" },
      { nome: "McDonnell Douglas MD-90-30ER" },
      { nome: "Mitsubish Regional Jet" },
      { nome: "Saab 2000" },
      { nome: "Sunkhoi Superjet 100" },
      { nome: "Tupolev Tu-104" },
      { nome: "Tupolev Tu-114" },
      { nome: "Tupolev Tu-124" },
      { nome: "Tupolev Tu-134" },
      { nome: "Tupolev Tu-144" },
      { nome: "Tupolev Tu-154" },
      { nome: "Tupolev Tu-204" },
      { nome: "Tupolev Tu-334" },
      { nome: "Vickers VC.1 Viking" },
      { nome: "Vickers Viscont" },
      { nome: "Vickers vanguard" },
      { nome: "Vickers VC-10" },
      { nome: "Xian MA60" },
      { nome: "Yakolev Yak-40" },
      { nome: "Yakolev Yak-42" },
    ]);
  }
}

module.exports = ModeloSeeder;
