"use strict";

/*
|--------------------------------------------------------------------------
| AeronaveCategoriaSeeder
|--------------------------------------------------------------------------
|
| Make use of the Factory instance to seed database with dummy data or
| make use of Lucid models directly.
|
*/

/** @type {import('@adonisjs/lucid/src/Factory')} */
const Factory = use("Factory");
const AeronaveCategoria = use("App/Models/AeronavesCategoria");

class AeronaveCategoriaSeeder {
  async run() {
    await AeronaveCategoria.createMany([
      { aeronave_id: 1, categoria_id: 4 },
      { aeronave_id: 2, categoria_id: 4 },
      { aeronave_id: 3, categoria_id: 4 },
      { aeronave_id: 4, categoria_id: 4 },
      { aeronave_id: 5, categoria_id: 4 },
      { aeronave_id: 6, categoria_id: 4 },
      { aeronave_id: 7, categoria_id: 4 },
      { aeronave_id: 7, categoria_id: 4 },
      { aeronave_id: 9, categoria_id: 4 },
      { aeronave_id: 10, categoria_id: 4 },
      { aeronave_id: 11, categoria_id: 4 },
      { aeronave_id: 12, categoria_id: 4 },
      { aeronave_id: 13, categoria_id: 7 },
      { aeronave_id: 14, categoria_id: 7 },
      { aeronave_id: 15, categoria_id: 7 },
      { aeronave_id: 16, categoria_id: 7 },
      { aeronave_id: 17, categoria_id: 7 },
      { aeronave_id: 18, categoria_id: 7 },
      { aeronave_id: 19, categoria_id: 7 },
      { aeronave_id: 20, categoria_id: 4 },
      { aeronave_id: 21, categoria_id: 7 },
      { aeronave_id: 22, categoria_id: 7 },
      { aeronave_id: 23, categoria_id: 7 },
      { aeronave_id: 24, categoria_id: 4 },
      { aeronave_id: 25, categoria_id: 4 },
      { aeronave_id: 26, categoria_id: 4 },
      { aeronave_id: 27, categoria_id: 4 },
      { aeronave_id: 28, categoria_id: 4 },
      { aeronave_id: 29, categoria_id: 4 },
      { aeronave_id: 30, categoria_id: 4 },
      { aeronave_id: 31, categoria_id: 4 },
      { aeronave_id: 32, categoria_id: 4 },
      { aeronave_id: 33, categoria_id: 4 },
      { aeronave_id: 34, categoria_id: 4 },
      { aeronave_id: 35, categoria_id: 4 },
      { aeronave_id: 36, categoria_id: 4 },
      { aeronave_id: 37, categoria_id: 4 },
      { aeronave_id: 37, categoria_id: 4 },
      { aeronave_id: 39, categoria_id: 4 },
      { aeronave_id: 40, categoria_id: 4 },
      { aeronave_id: 41, categoria_id: 4 },
      { aeronave_id: 42, categoria_id: 4 },
      { aeronave_id: 43, categoria_id: 4 },
      { aeronave_id: 44, categoria_id: 4 },
      { aeronave_id: 45, categoria_id: 4 },
      { aeronave_id: 46, categoria_id: 4 },
      { aeronave_id: 47, categoria_id: 4 },
      { aeronave_id: 48, categoria_id: 4 },
      { aeronave_id: 49, categoria_id: 4 },
      { aeronave_id: 50, categoria_id: 4 },
      { aeronave_id: 51, categoria_id: 4 },
      { aeronave_id: 52, categoria_id: 4 },
      { aeronave_id: 53, categoria_id: 4 },
      { aeronave_id: 54, categoria_id: 4 },
      { aeronave_id: 55, categoria_id: 4 },
      { aeronave_id: 56, categoria_id: 4 },
      { aeronave_id: 57, categoria_id: 4 },
      { aeronave_id: 58, categoria_id: 4 },
      { aeronave_id: 59, categoria_id: 4 },
      { aeronave_id: 60, categoria_id: 4 },
      { aeronave_id: 61, categoria_id: 4 },
      { aeronave_id: 62, categoria_id: 4 },
      { aeronave_id: 63, categoria_id: 4 },
      { aeronave_id: 64, categoria_id: 4 },
      { aeronave_id: 65, categoria_id: 4 },
      { aeronave_id: 66, categoria_id: 7 },
      { aeronave_id: 67, categoria_id: 7 },
      { aeronave_id: 68, categoria_id: 7 },
      { aeronave_id: 69, categoria_id: 7 },
      { aeronave_id: 70, categoria_id: 7 },
      { aeronave_id: 71, categoria_id: 3 },
      { aeronave_id: 72, categoria_id: 3 },
      { aeronave_id: 73, categoria_id: 3 },
      { aeronave_id: 74, categoria_id: 3 },
      { aeronave_id: 75, categoria_id: 3 },
      { aeronave_id: 76, categoria_id: 3 },
      { aeronave_id: 77, categoria_id: 3 },
      { aeronave_id: 78, categoria_id: 3 },
      { aeronave_id: 79, categoria_id: 3 },
      { aeronave_id: 70, categoria_id: 3 },
      { aeronave_id: 71, categoria_id: 3 },
      { aeronave_id: 72, categoria_id: 3 },
      { aeronave_id: 73, categoria_id: 3 },
      { aeronave_id: 74, categoria_id: 3 },
      { aeronave_id: 75, categoria_id: 3 },
      { aeronave_id: 76, categoria_id: 3 },
      { aeronave_id: 77, categoria_id: 3 },
      { aeronave_id: 78, categoria_id: 3 },
      { aeronave_id: 79, categoria_id: 3 },
      { aeronave_id: 90, categoria_id: 3 },
      { aeronave_id: 91, categoria_id: 3 },
      { aeronave_id: 92, categoria_id: 3 },
      { aeronave_id: 93, categoria_id: 3 },
      { aeronave_id: 94, categoria_id: 3 },
      { aeronave_id: 95, categoria_id: 3 },
      { aeronave_id: 96, categoria_id: 3 },
      { aeronave_id: 97, categoria_id: 3 },
      { aeronave_id: 98, categoria_id: 3 },
      { aeronave_id: 99, categoria_id: 3 },
      { aeronave_id: 100, categoria_id: 3 },
      { aeronave_id: 101, categoria_id: 3 },
      { aeronave_id: 102, categoria_id: 3 },
      { aeronave_id: 103, categoria_id: 4 },
      { aeronave_id: 104, categoria_id: 4 },
      { aeronave_id: 105, categoria_id: 5 },
      { aeronave_id: 106, categoria_id: 7 },
      { aeronave_id: 107, categoria_id: 7 },
      { aeronave_id: 108, categoria_id: 7 },
      { aeronave_id: 109, categoria_id: 7 },
      { aeronave_id: 100, categoria_id: 7 },
      { aeronave_id: 111, categoria_id: 7 },
      { aeronave_id: 112, categoria_id: 7 },
      { aeronave_id: 113, categoria_id: 7 },
      { aeronave_id: 114, categoria_id: 7 },
      { aeronave_id: 115, categoria_id: 7 },
      { aeronave_id: 116, categoria_id: 7 },
      { aeronave_id: 117, categoria_id: 7 },
      { aeronave_id: 118, categoria_id: 7 },
      { aeronave_id: 119, categoria_id: 7 },
      { aeronave_id: 120, categoria_id: 7 },
      { aeronave_id: 121, categoria_id: 7 },
      { aeronave_id: 122, categoria_id: 7 },
      { aeronave_id: 123, categoria_id: 7 },
      { aeronave_id: 124, categoria_id: 7 },
      { aeronave_id: 125, categoria_id: 7 },
      { aeronave_id: 126, categoria_id: 7 },
      { aeronave_id: 127, categoria_id: 4 },
      { aeronave_id: 128, categoria_id: 4 },
      { aeronave_id: 129, categoria_id: 4 },
      { aeronave_id: 130, categoria_id: 4 },
      { aeronave_id: 131, categoria_id: 4 },
      { aeronave_id: 132, categoria_id: 4 },
      { aeronave_id: 133, categoria_id: 4 },
      { aeronave_id: 134, categoria_id: 4 },
      { aeronave_id: 135, categoria_id: 4 },
      { aeronave_id: 136, categoria_id: 4 },
      { aeronave_id: 137, categoria_id: 4 },
      { aeronave_id: 138, categoria_id: 4 },
      { aeronave_id: 139, categoria_id: 4 },
      { aeronave_id: 140, categoria_id: 7 },
      { aeronave_id: 141, categoria_id: 7 },
      { aeronave_id: 142, categoria_id: 7 },
      { aeronave_id: 143, categoria_id: 7 },
      { aeronave_id: 144, categoria_id: 7 },
      { aeronave_id: 145, categoria_id: 4 },
      { aeronave_id: 146, categoria_id: 4 },
      { aeronave_id: 147, categoria_id: 4 },
      { aeronave_id: 148, categoria_id: 4 },
      { aeronave_id: 149, categoria_id: 7 },
      { aeronave_id: 150, categoria_id: 7 },
      { aeronave_id: 151, categoria_id: 7 },
      { aeronave_id: 152, categoria_id: 7 },
      { aeronave_id: 153, categoria_id: 7 },
      { aeronave_id: 154, categoria_id: 7 },
      { aeronave_id: 155, categoria_id: 7 },
      { aeronave_id: 156, categoria_id: 7 },
      { aeronave_id: 157, categoria_id: 7 },
      { aeronave_id: 158, categoria_id: 4 },
      { aeronave_id: 159, categoria_id: 4 },
      { aeronave_id: 160, categoria_id: 4 },
      { aeronave_id: 161, categoria_id: 4 },
      { aeronave_id: 162, categoria_id: 4 },
      { aeronave_id: 163, categoria_id: 4 },
      { aeronave_id: 164, categoria_id: 4 },
      { aeronave_id: 165, categoria_id: 4 },
      { aeronave_id: 166, categoria_id: 4 },
      { aeronave_id: 167, categoria_id: 4 },
      { aeronave_id: 168, categoria_id: 4 },
      { aeronave_id: 169, categoria_id: 4 },
      { aeronave_id: 170, categoria_id: 4 },
      { aeronave_id: 171, categoria_id: 4 },
      { aeronave_id: 172, categoria_id: 7 },
      { aeronave_id: 173, categoria_id: 4 },
      { aeronave_id: 174, categoria_id: 4 },
      { aeronave_id: 175, categoria_id: 4 },
      { aeronave_id: 176, categoria_id: 4 },
      { aeronave_id: 177, categoria_id: 4 },
      { aeronave_id: 178, categoria_id: 4 },
      { aeronave_id: 179, categoria_id: 4 },
      { aeronave_id: 180, categoria_id: 4 },
      { aeronave_id: 181, categoria_id: 4 },
      { aeronave_id: 182, categoria_id: 7 },
      { aeronave_id: 183, categoria_id: 7 },
      { aeronave_id: 184, categoria_id: 7 },
      { aeronave_id: 185, categoria_id: 7 },
      { aeronave_id: 186, categoria_id: 7 },
      { aeronave_id: 187, categoria_id: 4 },
      { aeronave_id: 188, categoria_id: 4 },
    ]);
  }
}

module.exports = AeronaveCategoriaSeeder;
